name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 #fetch code from github repo
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run TestWithReportGeneration
          browser: chrome
          
      - name: Upload Report on GitHub Actions
        uses: actions/upload-artifact@v2
        with:
          name: HTML_Report
          path: cypress/reports/Results
          retention-days: 2 